# List all available targets
help:
	@echo "Available targets:"
	@echo "  help          - Show this help message"
	@echo "  dev           - Start development server"
	@echo "  start         - Start development server (alias for dev)"
	@echo "  build         - Build for production"
	@echo "  preview       - Preview production build locally"
	@echo "  sync          - Generate TypeScript types for Astro"
	@echo "  upgrade       - Upgrade Astro"
	@echo "  upgrade-patch - Upgrade patch versions interactively"
	@echo "  upgrade-minor - Upgrade minor versions interactively"
	@echo "  upgrade-major - Upgrade major versions interactively"
	@echo "  upgrade-latest - Upgrade to latest versions"
	@echo "  outdated      - Show outdated dependencies"
	@echo "  dedupe        - Deduplicate dependencies in node_modules"
	@echo "  prune         - Remove extraneous packages"
	@echo "  audit         - Audit dependencies for security vulnerabilities"
	@echo "  test          - Run tests"
	@echo "  test-report   - Show test report"
	@echo "  unit-test     - Run unit tests"
	@echo "  test-coverage - Run tests with coverage"
	@echo "  test-watch    - Run tests in watch mode"
	@echo "  install       - Install dependencies"
	@echo "  clean         - Clean build artifacts"
	@echo "  format        - Format code"
	@echo "  lint          - Lint code"
	@echo "  check         - Check types"
	@echo "  check-all     - Run all checks"
	@echo "  partykit-dev  - Start PartyKit development server"
	@echo "  partykit-deploy - Deploy PartyKit"
	@echo "  partykit-login - Login to PartyKit"
	@echo "  partykit-logout - Logout from PartyKit"
	@echo "  dev-all       - Run both Astro and PartyKit dev servers"
	@echo "  kill-all      - Kill all PartyKit and Astro processes"
	@echo ""
	@echo "Git Commands:"
	@echo "  git-status    - Show git status in short format"
	@echo "  git-log       - Show pretty git log with graph"
	@echo "  git-bisect-start - Start git bisect process"
	@echo "  git-bisect-good - Mark current commit as good in bisect"
	@echo "  git-bisect-bad  - Mark current commit as bad in bisect"
	@echo "  git-bisect-reset - Reset git bisect process"
	@echo "  git-stash-save  - Save changes to stash with message"
	@echo "  git-stash-list  - List all stashes"
	@echo "  git-stash-pop   - Apply and remove latest stash"
	@echo "  git-stash-apply - Apply specific stash"
	@echo "  git-branch-create - Create and checkout new branch"
	@echo "  git-branch-delete - Delete a branch"
	@echo "  git-branch-list   - List all branches"
	@echo "  git-prune      - Prune remote branches"
	@echo "  git-cleanup    - Clean up deleted remote branches"
	@echo "  git-reflog     - Show reference logs"
	@echo "  git-find-in-history - Find text in git history"
	@echo "  git-blame      - Show who changed what in a file"
	@echo "  git-cherry-pick - Cherry-pick a commit"
	@echo "  git-rebase-interactive - Interactive rebase"
	@echo "  git-worktree-list   - List worktrees"
	@echo "  git-worktree-add    - Add a worktree"
	@echo "  git-worktree-remove - Remove a worktree"
	@echo "  git-submodule-add   - Add a new git submodule"
	@echo "  git-submodule-update - Update all submodules"
	@echo "  git-submodule-pull-all - Pull main repo and all submodules"
	@echo "  git-submodule-status - Check status of all submodules"
	@echo "  git-submodule-remove - Remove a submodule"
	@echo "  git-hooks-list   - List git hooks"
	@echo "  git-difftool    - Diff a file with external tool"
	@echo "  git-show-file   - Show file at specific commit"

default: help
